label:
  service: "${SERVICE:vulcan.gate.interface}"
  profile: "${PROFILE:DEV}"
  color: "${COLOR:local}"
  node: "${NODE}"
  encrypted: true
  language: "${LANGUAGE:en}"
trace:
  endpoint: http://localhost:14268/api/traces
log:
  type: zap
  level: debug
server:
  tcp:
    addr: 0.0.0.0:7001
  http:
    addr: 0.0.0.0:8100
    timeout: 0.5s
  grpc:
    addr: 0.0.0.0:9100
    timeout: 0.5s
data:
  redis:
    addr: localhost:6379
    password: vulcan_hammer
    dial_timeout: 2s
    read_timeout: 0.5s
    write_timeout: 0.5s
